In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("call_activity.csv")
df

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,99.0,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False
1,OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,103.0,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False
2,NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,110.0,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False
3,OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,88.0,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False
4,OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,122.0,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,AZ,192,415,No,Yes,36,156.2,77.0,26.55,215.5,126.0,18.32,279.1,83.0,12.56,9.9,6,2.67,2.0,False
3329,WV,68,415,No,No,0,231.1,57.0,39.29,153.4,55.0,13.04,191.3,123.0,8.61,9.6,4,2.59,3.0,False
3330,RI,28,510,No,No,0,180.8,109.0,30.74,288.8,58.0,24.55,191.9,91.0,8.64,14.1,6,3.81,2.0,False
3331,CT,184,510,Yes,No,0,213.8,105.0,36.35,159.6,84.0,13.57,139.2,137.0,6.26,5.0,10,1.35,2.0,False
3332,TN,74,415,No,Yes,25,234.4,113.0,39.85,265.9,82.0,22.60,241.4,77.0,10.86,13.7,4,3.70,0.0,False

In [4]:
df.head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,99.0,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False
1,OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,103.0,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False
2,NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,110.0,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False
3,OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,88.0,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False
4,OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,122.0,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False

In [5]:
df.tail()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
3328,AZ,192,415,No,Yes,36,156.2,77.0,26.55,215.5,126.0,18.32,279.1,83.0,12.56,9.9,6,2.67,2.0,False
3329,WV,68,415,No,No,0,231.1,57.0,39.29,153.4,55.0,13.04,191.3,123.0,8.61,9.6,4,2.59,3.0,False
3330,RI,28,510,No,No,0,180.8,109.0,30.74,288.8,58.0,24.55,191.9,91.0,8.64,14.1,6,3.81,2.0,False
3331,CT,184,510,Yes,No,0,213.8,105.0,36.35,159.6,84.0,13.57,139.2,137.0,6.26,5.0,10,1.35,2.0,False
3332,TN,74,415,No,Yes,25,234.4,113.0,39.85,265.9,82.0,22.60,241.4,77.0,10.86,13.7,4,3.70,0.0,False

In [6]:
dictdf = {
    "Name": ['John', 'Mike', 'Bob'],
    "Desg": ['SDE', 'Desginer', 'CEO'],
    "salary": [100000, 80000, 200000]
}

In [7]:
tempdf = pd.DataFrame.from_dict(dictdf)

In [8]:
tempdf

   Name      Desg  salary
0  John       SDE  100000
1  Mike  Desginer   80000
2   Bob       CEO  200000

In [9]:
tempdf.columns

Index(['Name', 'Desg', 'salary'], dtype='str')

In [10]:
tempdf.dtypes

Name        str
Desg        str
salary    int64
dtype: object

In [11]:
tempdf.Name

0    John
1    Mike
2     Bob
Name: Name, dtype: str

In [13]:
df[('Name', 'Desg')]

KeyError: ('Name', 'Desg')

In [14]:
tempdf[['Name', 'Desg']]

   Name      Desg
0  John       SDE
1  Mike  Desginer
2   Bob       CEO

In [16]:
tempdf[tempdf['Name'] == 'John']

   Name Desg  salary
0  John  SDE  100000

In [18]:
df[df['State'] == 'NJ']

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
2,NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,110.0,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False
39,NJ,149,408,No,No,0,140.4,94.0,23.87,271.8,92.0,23.10,188.3,108.0,8.47,11.1,9,3.00,1.0,False
70,NJ,138,408,No,No,0,241.8,93.0,41.11,170.5,83.0,14.49,295.3,104.0,13.29,11.8,7,3.19,3.0,False
89,NJ,128,415,No,No,0,237.9,125.0,40.44,247.6,93.0,21.05,208.9,68.0,9.40,13.9,4,3.75,1.0,True
116,NJ,64,510,No,No,0,162.6,83.0,27.64,152.3,109.0,12.95,57.5,122.0,2.59,14.2,3,3.83,1.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3034,NJ,75,415,No,Yes,42,248.9,93.0,42.31,170.8,108.0,14.52,104.5,91.0,4.70,11.2,8,3.02,1.0,False
3126,NJ,108,415,No,No,0,239.3,102.0,40.68,223.4,127.0,18.99,251.4,104.0,11.31,10.6,6,2.86,0.0,False
3136,NJ,107,408,No,Yes,36,96.3,83.0,16.37,179.6,91.0,15.27,166.3,121.0,7.48,10.3,2,2.78,1.0,False
3248,NJ,93,415,No,No,0,146.3,85.0,24.87,216.6,95.0,18.41,233.0,82.0,10.49,11.5,3,3.11,0.0,False
3279,NJ,139,415,No,Yes,43,231.0,85.0,39.27,222.3,82.0,18.90,148.0,105.0,6.66,8.3,5,2.24,2.0,False

In [19]:
df[(df['State'] == 'NJ') & (df['Voice mail plan'] == 'Yes')]

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
527,NJ,95,415,No,Yes,22,40.9,126.0,6.95,133.4,90.0,11.34,264.2,91.0,11.89,11.9,7,3.21,0.0,False
626,NJ,95,408,Yes,Yes,37,220.2,109.0,37.43,185.3,99.0,15.75,205.1,82.0,9.23,4.1,2,1.11,0.0,True
633,NJ,122,415,No,Yes,34,146.4,104.0,24.89,89.7,103.0,7.62,220.0,91.0,9.90,15.6,4,4.21,2.0,False
693,NJ,92,510,No,Yes,29,155.4,110.0,26.42,188.5,104.0,16.02,254.9,118.0,11.47,8.0,4,2.16,3.0,False
734,NJ,93,415,Yes,Yes,20,187.5,110.0,31.88,169.8,94.0,14.43,175.3,127.0,7.89,12.1,4,3.27,1.0,False
910,NJ,42,415,No,Yes,32,163.8,80.0,27.85,177.8,123.0,15.11,190.4,106.0,8.57,8.1,5,2.19,0.0,False
966,NJ,48,510,No,Yes,22,152.0,63.0,25.84,258.8,131.0,22.00,263.2,109.0,11.84,15.7,5,4.24,2.0,True
1105,NJ,135,510,No,Yes,28,201.4,100.0,34.24,246.5,117.0,20.95,154.8,131.0,6.97,12.9,4,3.48,2.0,True
1409,NJ,1,415,No,Yes,30,183.1,95.0,31.13,232.6,110.0,19.77,248.3,110.0,11.17,8.4,2,2.27,0.0,False
1479,NJ,66,415,No,Yes,16,174.7,92.0,29.70,232.1,105.0,19.73,305.4,98.0,13.74,8.9,2,2.40,1.0,False
1802,NJ,147,415,No,Yes,36,254.2,78.0,43.21,228.1,105.0,19.39,98.0,125.0,4.41,13.8,7,3.73,5.0,False
1903,NJ,93,510,Yes,Yes,38,225.7,117.0,38.37,119.6,122.0,10.17,193.2,125.0,8.69,14.0,7,3.78,1.0,True
2293,NJ,59,510,Yes,Yes,31,225.0,78.0,38.25,191.3,79.0,16.26,226.7,79.0,10.20,9.1,3,2.46,1.0,False
2667,NJ,136,408,No,Yes,27,187.7,84.0,31.91,221.0,147.0,18.79,145.7,110.0,6.56,10.0,4,2.70,3.0,False
2730,NJ,156,408,No,Yes,27,192.3,137.0,32.69,199.9,115.0,16.99,244.2,112.0,10.99,14.8,8,4.00,1.0,False
2773,NJ,134,510,No,Yes,34,247.2,105.0,42.02,225.5,133.0,19.17,186.3,76.0,8.38,6.1,5,1.65,2.0,True
2840,NJ,108,415,No,Yes,41,171.6,110.0,29.17,136.1,78.0,11.57,183.4,103.0,8.25,10.8,7,2.92,0.0,False
3034,NJ,75,415,No,Yes,42,248.9,93.0,42.31,170.8,108.0,14.52,104.5,91.0,4.70,11.2,8,3.02,1.0,False
3136,NJ,107,408,No,Yes,36,96.3,83.0,16.37,179.6,91.0,15.27,166.3,121.0,7.48,10.3,2,2.78,1.0,False
3279,NJ,139,415,No,Yes,43,231.0,85.0,39.27,222.3,82.0,18.90,148.0,105.0,6.66,8.3,5,2.24,2.0,False

In [20]:
df.iloc(15)

ValueError: No axis named 15 for object type DataFrame

In [21]:
df.iloc[15]

State                        NY
Account length              161
Area code                   415
International plan           No
Voice mail plan              No
Number vmail messages         0
Total day minutes           NaN
Total day calls             NaN
Total day charge            NaN
Total eve minutes         317.8
Total eve calls            97.0
Total eve charge          27.01
Total night minutes       160.6
Total night calls         128.0
Total night charge         7.23
Total intl minutes          5.4
Total intl calls              9
Total intl charge          1.46
Customer service calls      4.0
Churn                      True
Name: 15, dtype: object

In [22]:
df.iloc[15,4]

'No'

In [23]:
df.iloc[15, 11]

np.float64(27.01)

In [24]:
df.iloc[15:25]

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
15,NY,161,415,No,No,0,NaN,NaN,NaN,317.8,97.0,27.01,160.6,128.0,7.23,5.4,9,1.46,4.0,True
16,ID,85,408,No,Yes,27,NaN,NaN,NaN,280.9,90.0,23.88,89.3,NaN,4.02,13.8,4,3.73,1.0,False
17,VT,93,510,No,No,0,NaN,NaN,NaN,218.2,111.0,18.55,129.6,121.0,5.83,8.1,3,2.19,3.0,False
18,VA,76,510,No,Yes,33,NaN,NaN,NaN,212.8,65.0,18.09,165.7,108.0,7.46,10.0,5,2.70,1.0,False
19,TX,73,415,No,No,0,NaN,NaN,NaN,NaN,88.0,13.56,192.8,74.0,8.68,13.0,2,3.51,1.0,False
20,FL,147,415,No,No,0,NaN,NaN,NaN,239.7,93.0,20.37,208.8,133.0,9.40,10.6,4,2.86,0.0,False
21,CO,77,408,No,No,0,NaN,NaN,NaN,169.9,121.0,14.44,209.6,64.0,9.43,5.7,6,1.54,5.0,True
22,AZ,130,415,No,No,0,183.0,112.0,31.11,72.9,99.0,6.20,181.8,78.0,8.18,9.5,19,2.57,0.0,NaN
23,SC,111,415,No,No,0,110.4,103.0,18.77,137.3,102.0,11.67,189.6,105.0,8.53,7.7,6,2.08,2.0,False
24,VA,132,510,No,No,0,81.1,86.0,13.79,245.2,72.0,20.84,237.0,115.0,10.67,10.3,2,2.78,0.0,False

In [25]:
state = df.copy()

In [26]:
state.set_index('State', inplace = True)

In [27]:
state.loc['NJ']

,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
State,,,,,,,,,,,,,,,,,,,
NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,110.0,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False
NJ,149,408,No,No,0,140.4,94.0,23.87,271.8,92.0,23.10,188.3,108.0,8.47,11.1,9,3.00,1.0,False
NJ,138,408,No,No,0,241.8,93.0,41.11,170.5,83.0,14.49,295.3,104.0,13.29,11.8,7,3.19,3.0,False
NJ,128,415,No,No,0,237.9,125.0,40.44,247.6,93.0,21.05,208.9,68.0,9.40,13.9,4,3.75,1.0,True
NJ,64,510,No,No,0,162.6,83.0,27.64,152.3,109.0,12.95,57.5,122.0,2.59,14.2,3,3.83,1.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
NJ,75,415,No,Yes,42,248.9,93.0,42.31,170.8,108.0,14.52,104.5,91.0,4.70,11.2,8,3.02,1.0,False
NJ,108,415,No,No,0,239.3,102.0,40.68,223.4,127.0,18.99,251.4,104.0,11.31,10.6,6,2.86,0.0,False
NJ,107,408,No,Yes,36,96.3,83.0,16.37,179.6,91.0,15.27,166.3,121.0,7.48,10.3,2,2.78,1.0,False
NJ,93,415,No,No,0,146.3,85.0,24.87,216.6,95.0,18.41,233.0,82.0,10.49,11.5,3,3.11,0.0,False
NJ,139,415,No,Yes,43,231.0,85.0,39.27,222.3,82.0,18.90,148.0,105.0,6.66,8.3,5,2.24,2.0,False

In [28]:
state.reset_index()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,99.0,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False
1,OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,103.0,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False
2,NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,110.0,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False
3,OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,88.0,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False
4,OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,122.0,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,AZ,192,415,No,Yes,36,156.2,77.0,26.55,215.5,126.0,18.32,279.1,83.0,12.56,9.9,6,2.67,2.0,False
3329,WV,68,415,No,No,0,231.1,57.0,39.29,153.4,55.0,13.04,191.3,123.0,8.61,9.6,4,2.59,3.0,False
3330,RI,28,510,No,No,0,180.8,109.0,30.74,288.8,58.0,24.55,191.9,91.0,8.64,14.1,6,3.81,2.0,False
3331,CT,184,510,Yes,No,0,213.8,105.0,36.35,159.6,84.0,13.57,139.2,137.0,6.26,5.0,10,1.35,2.0,False
3332,TN,74,415,No,Yes,25,234.4,113.0,39.85,265.9,82.0,22.60,241.4,77.0,10.86,13.7,4,3.70,0.0,False

In [29]:
df.isnull()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3329,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3330,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3331,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3332,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [30]:
df

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,99.0,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False
1,OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,103.0,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False
2,NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,110.0,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False
3,OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,88.0,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False
4,OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,122.0,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,AZ,192,415,No,Yes,36,156.2,77.0,26.55,215.5,126.0,18.32,279.1,83.0,12.56,9.9,6,2.67,2.0,False
3329,WV,68,415,No,No,0,231.1,57.0,39.29,153.4,55.0,13.04,191.3,123.0,8.61,9.6,4,2.59,3.0,False
3330,RI,28,510,No,No,0,180.8,109.0,30.74,288.8,58.0,24.55,191.9,91.0,8.64,14.1,6,3.81,2.0,False
3331,CT,184,510,Yes,No,0,213.8,105.0,36.35,159.6,84.0,13.57,139.2,137.0,6.26,5.0,10,1.35,2.0,False
3332,TN,74,415,No,Yes,25,234.4,113.0,39.85,265.9,82.0,22.60,241.4,77.0,10.86,13.7,4,3.70,0.0,False

In [31]:
df.columns.isnull().sum()

np.int64(0)

In [33]:
df.columns

Index(['State', 'Account length', 'Area code', 'International plan',
       'Voice mail plan', 'Number vmail messages', 'Total day minutes',
       'Total day calls', 'Total day charge', 'Total eve minutes',
       'Total eve calls', 'Total eve charge', 'Total night minutes',
       'Total night calls', 'Total night charge', 'Total intl minutes',
       'Total intl calls', 'Total intl charge', 'Customer service calls',
       'Churn'],
      dtype='str')

In [34]:
df.isnull().sum()

State                      0
Account length             0
Area code                  0
International plan         0
Voice mail plan            0
Number vmail messages      0
Total day minutes         10
Total day calls           10
Total day charge          18
Total eve minutes          9
Total eve calls            8
Total eve charge           0
Total night minutes        0
Total night calls          1
Total night charge         0
Total intl minutes         0
Total intl calls           0
Total intl charge          5
Customer service calls     5
Churn                      8
dtype: int64

In [36]:
df.dropna(inplace = True)

In [37]:
df

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,99.0,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False
1,OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,103.0,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False
2,NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,110.0,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False
3,OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,88.0,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False
4,OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,122.0,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,AZ,192,415,No,Yes,36,156.2,77.0,26.55,215.5,126.0,18.32,279.1,83.0,12.56,9.9,6,2.67,2.0,False
3329,WV,68,415,No,No,0,231.1,57.0,39.29,153.4,55.0,13.04,191.3,123.0,8.61,9.6,4,2.59,3.0,False
3330,RI,28,510,No,No,0,180.8,109.0,30.74,288.8,58.0,24.55,191.9,91.0,8.64,14.1,6,3.81,2.0,False
3331,CT,184,510,Yes,No,0,213.8,105.0,36.35,159.6,84.0,13.57,139.2,137.0,6.26,5.0,10,1.35,2.0,False
3332,TN,74,415,No,Yes,25,234.4,113.0,39.85,265.9,82.0,22.60,241.4,77.0,10.86,13.7,4,3.70,0.0,False

In [38]:
df.isnull().sum()

State                     0
Account length            0
Area code                 0
International plan        0
Voice mail plan           0
Number vmail messages     0
Total day minutes         0
Total day calls           0
Total day charge          0
Total eve minutes         0
Total eve calls           0
Total eve charge          0
Total night minutes       0
Total night calls         0
Total night charge        0
Total intl minutes        0
Total intl calls          0
Total intl charge         0
Customer service calls    0
Churn                     0
dtype: int64

In [39]:
df.drop('Churn', axis=1)

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls
0,KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,99.0,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0
1,OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,103.0,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0
2,NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,110.0,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0
3,OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,88.0,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0
4,OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,122.0,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,AZ,192,415,No,Yes,36,156.2,77.0,26.55,215.5,126.0,18.32,279.1,83.0,12.56,9.9,6,2.67,2.0
3329,WV,68,415,No,No,0,231.1,57.0,39.29,153.4,55.0,13.04,191.3,123.0,8.61,9.6,4,2.59,3.0
3330,RI,28,510,No,No,0,180.8,109.0,30.74,288.8,58.0,24.55,191.9,91.0,8.64,14.1,6,3.81,2.0
3331,CT,184,510,Yes,No,0,213.8,105.0,36.35,159.6,84.0,13.57,139.2,137.0,6.26,5.0,10,1.35,2.0
3332,TN,74,415,No,Yes,25,234.4,113.0,39.85,265.9,82.0,22.60,241.4,77.0,10.86,13.7,4,3.70,0.0

In [40]:
df['Total charge'] = df['Total day charge'] + df['Total night charge']

In [41]:
df

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,...,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn,Total charge
0,KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,...,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False,56.08
1,OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,...,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False,38.92
2,NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,...,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False,48.70
3,OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,...,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False,59.76
4,OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,...,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False,36.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,AZ,192,415,No,Yes,36,156.2,77.0,26.55,215.5,...,18.32,279.1,83.0,12.56,9.9,6,2.67,2.0,False,39.11
3329,WV,68,415,No,No,0,231.1,57.0,39.29,153.4,...,13.04,191.3,123.0,8.61,9.6,4,2.59,3.0,False,47.90
3330,RI,28,510,No,No,0,180.8,109.0,30.74,288.8,...,24.55,191.9,91.0,8.64,14.1,6,3.81,2.0,False,39.38
3331,CT,184,510,Yes,No,0,213.8,105.0,36.35,159.6,...,13.57,139.2,137.0,6.26,5.0,10,1.35,2.0,False,42.61
3332,TN,74,415,No,Yes,25,234.4,113.0,39.85,265.9,...,22.60,241.4,77.0,10.86,13.7,4,3.70,0.0,False,50.71

In [42]:
df.iloc[0,-1] = 70

In [43]:
df.iloc[0,-1]

np.float64(70.0)

In [44]:
df.iloc[0]

State                        KS
Account length              128
Area code                   415
International plan           No
Voice mail plan             Yes
Number vmail messages        25
Total day minutes         265.1
Total day calls           110.0
Total day charge          45.07
Total eve minutes         197.4
Total eve calls            99.0
Total eve charge          16.78
Total night minutes       244.7
Total night calls          91.0
Total night charge        11.01
Total intl minutes         10.0
Total intl calls              3
Total intl charge           2.7
Customer service calls      1.0
Churn                     False
Total charge               70.0
Name: 0, dtype: object

In [45]:
df.to_json('output.json')